package br.com.acmattos.hdc.scheduler.config

import br.com.acmattos.hdc.common.tool.server.javalin.ErrorTrackerCode

/**
 * @author ACMattos
 * @since 27/10/2021.
 */
enum class ErrorTrackerCodeEnum(val code: ErrorTrackerCode) {
    SCHEDULE_ALREADY_DEFINED(ErrorTrackerCode("01FJZAH7JVKTN1BYZW6BRHFZFJ")),
    DENTIST_NOT_REGISTERED(ErrorTrackerCode("01FKXA1PFXQ2MJX8PESM4KVKSP")),
    FROM_BIGGER_THAN_TO(ErrorTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    OPERATION_GENERATES_REMINDER(ErrorTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    SLOT_BELLOW_ONE(ErrorTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    FROM_LESS_THAN_TO(ErrorTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    VALID_SLOT(ErrorTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    DURATION_CREATES_PERFECT_SLOTS(ErrorTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    WEEK_DAY_CONVERT_FAILED(ErrorTrackerCode("01FJZEYS51KTN1BYZW6BRHFZFJ")),
    NO_PERIODS_DEFINED(ErrorTrackerCode("01FJZEXFENKTN1BYZW6BRHFZFJ")),
    THERE_IS_A_COLLISION(ErrorTrackerCode("01FJZEY8ASKTN1BYZW6BRHFZFJ")),
}
