package br.com.acmattos.hdc.scheduler.config

import br.com.acmattos.hdc.common.tool.server.javalin.ErrorTrackerCode

/**
 * @author ACMattos
 * @since 27/10/2021.
 */
enum class ErrorTrackerCodeEnum(val code: ErrorTrackerCode) {
    SCHEDULE_ALREADY_DEFINED(ErrorTrackerCode("01FJZAH7JVKTN1BYZW6BRHFZFJ")),
    SCHEDULE_NOT_DEFINED(ErrorTrackerCode("01FM88XYXM9FE3F55670TQCPE3")),
    OVERLAPPING_APPOINTMENT(ErrorTrackerCode("01FMMZRY96Q2MJX8PESM4KVKSP")),
    DENTIST_NOT_REGISTERED(ErrorTrackerCode("01FKXA1PFXQ2MJX8PESM4KVKSP")),
    FROM_BIGGER_THAN_TO(ErrorTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    OPERATION_GENERATES_REMINDER(ErrorTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    SLOT_BELLOW_ONE(ErrorTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    FROM_LESS_THAN_TO(ErrorTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    FROM_LESSER_OR_EQUAL_TO_TO(ErrorTrackerCode("01FM60AXZ59FE3F55670TQCPE3")),
    VALID_SLOT(ErrorTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    DURATION_CREATES_PERFECT_SLOTS(ErrorTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    WEEK_DAY_CONVERT_FAILED(ErrorTrackerCode("01FJZEYS51KTN1BYZW6BRHFZFJ")),
    APPOINTMENT_STATUS_CONVERT_FAILED(ErrorTrackerCode("01FM60GR4EQ2MJX8PESM4KVKSP")),
    NO_PERIODS_DEFINED(ErrorTrackerCode("01FJZEXFENKTN1BYZW6BRHFZFJ")),
    THERE_IS_A_COLLISION(ErrorTrackerCode("01FJZEY8ASKTN1BYZW6BRHFZFJ")),
    INVALID_DENTIST_FULL_NAME(ErrorTrackerCode("01FM8D9F8BQ2MJX8PESM4KVKSP")),
    INVALID_PATIENT_FULL_NAME(ErrorTrackerCode("01FMMA8XWZQ2MJX8PESM4KVKSP")),
    ENTITY_APPOINTMENT_STATUS_MUST_BE_FREED(ErrorTrackerCode("01FMMZRY979FE3F55670TQCPE3")),
    ENTITY_APPOINTMENT_ENABLED_MUST_BE_TRUE(ErrorTrackerCode("01FN4KS8QBQ2MJX8PESM4KVKSP")),
}
