package br.com.acmattos.hdc.scheduler.config

import br.com.acmattos.hdc.common.tool.server.javalin.MessageTrackerCode

/**
 * @author ACMattos
 * @since 27/10/2021.
 */
enum class MessageTrackerCodeEnum(val code: MessageTrackerCode) {
    SCHEDULE_ALREADY_DEFINED(MessageTrackerCode("01FJZAH7JVKTN1BYZW6BRHFZFJ")),
    SCHEDULE_NOT_DEFINED(MessageTrackerCode("01FM88XYXM9FE3F55670TQCPE3")),
    OVERLAPPING_APPOINTMENT(MessageTrackerCode("01FMMZRY96Q2MJX8PESM4KVKSP")),
    DENTIST_NOT_REGISTERED(MessageTrackerCode("01FKXA1PFXQ2MJX8PESM4KVKSP")),
    FROM_BIGGER_THAN_TO(MessageTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    OPERATION_GENERATES_REMINDER(MessageTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    SLOT_BELLOW_ONE(MessageTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    FROM_LESS_THAN_TO(MessageTrackerCode("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    FROM_LESSER_OR_EQUAL_TO_TO(MessageTrackerCode("01FM60AXZ59FE3F55670TQCPE3")),
    VALID_SLOT(MessageTrackerCode("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    DURATION_CREATES_PERFECT_SLOTS(MessageTrackerCode("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    WEEK_DAY_CONVERT_FAILED(MessageTrackerCode("01FJZEYS51KTN1BYZW6BRHFZFJ")),
    APPOINTMENT_STATUS_CONVERT_FAILED(MessageTrackerCode("01FM60GR4EQ2MJX8PESM4KVKSP")),
    NO_PERIODS_DEFINED(MessageTrackerCode("01FJZEXFENKTN1BYZW6BRHFZFJ")),
    THERE_IS_A_COLLISION(MessageTrackerCode("01FJZEY8ASKTN1BYZW6BRHFZFJ")),
    INVALID_DENTIST_FULL_NAME(MessageTrackerCode("01FM8D9F8BQ2MJX8PESM4KVKSP")),
    INVALID_PATIENT_FULL_NAME(MessageTrackerCode("01FMMA8XWZQ2MJX8PESM4KVKSP")),
    ENTITY_APPOINTMENT_STATUS_MUST_BE_FREED(MessageTrackerCode("01FMMZRY979FE3F55670TQCPE3")),
    ENTITY_APPOINTMENT_ENABLED_MUST_BE_TRUE(MessageTrackerCode("01FN4KS8QBQ2MJX8PESM4KVKSP")),
}
