package br.com.acmattos.hdc.scheduler.config

import br.com.acmattos.hdc.common.tool.server.javalin.MessageTracker
import br.com.acmattos.hdc.common.tool.server.javalin.MessageTrackerId

/**
 * @author ACMattos
 * @since 27/10/2021.
 */
enum class MessageTrackerCodeEnum(
    val messageTrackerId: MessageTrackerId
): MessageTracker {
    SCHEDULE_ALREADY_DEFINED(MessageTrackerId("01FJZAH7JVKTN1BYZW6BRHFZFJ")),
    SCHEDULE_NOT_DEFINED(MessageTrackerId("01FM88XYXM9FE3F55670TQCPE3")),
    OVERLAPPING_APPOINTMENT(MessageTrackerId("01FMMZRY96Q2MJX8PESM4KVKSP")),
    DENTIST_NOT_REGISTERED(MessageTrackerId("01FKXA1PFXQ2MJX8PESM4KVKSP")),
    FROM_BIGGER_THAN_TO(MessageTrackerId("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    OPERATION_GENERATES_REMINDER(MessageTrackerId("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    SLOT_BELLOW_ONE(MessageTrackerId("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    FROM_LESS_THAN_TO(MessageTrackerId("01FJZAHV5HKTN1BYZW6BRHFZFJ")),
    FROM_LESSER_OR_EQUAL_TO_TO(MessageTrackerId("01FM60AXZ59FE3F55670TQCPE3")),
    VALID_SLOT(MessageTrackerId("01FJZAJFMGKTN1BYZW6BRHFZFJ")),
    DURATION_CREATES_PERFECT_SLOTS(MessageTrackerId("01FJZAK70FKTN1BYZW6BRHFZFJ")),
    WEEK_DAY_CONVERT_FAILED(MessageTrackerId("01FJZEYS51KTN1BYZW6BRHFZFJ")),
    APPOINTMENT_STATUS_CONVERT_FAILED(MessageTrackerId("01FM60GR4EQ2MJX8PESM4KVKSP")),
    NO_PERIODS_DEFINED(MessageTrackerId("01FJZEXFENKTN1BYZW6BRHFZFJ")),
    THERE_IS_A_COLLISION(MessageTrackerId("01FJZEY8ASKTN1BYZW6BRHFZFJ")),
    INVALID_DENTIST_FULL_NAME(MessageTrackerId("01FM8D9F8BQ2MJX8PESM4KVKSP")),
    INVALID_PATIENT_FULL_NAME(MessageTrackerId("01FMMA8XWZQ2MJX8PESM4KVKSP")),
    ENTITY_APPOINTMENT_STATUS_MUST_BE_FREED(MessageTrackerId("01FMMZRY979FE3F55670TQCPE3")),
    ENTITY_APPOINTMENT_ENABLED_MUST_BE_TRUE(MessageTrackerId("01FN4KS8QBQ2MJX8PESM4KVKSP"));

    override fun trackerId() = this.messageTrackerId
}
