package br.com.acmattos.hdc.odontogram.config

import br.com.acmattos.hdc.common.tool.server.javalin.MessageTracker
import br.com.acmattos.hdc.common.tool.server.javalin.MessageTrackerId

enum class MessageTrackerIdEnum(
    val messageTrackerId: MessageTrackerId
): MessageTracker {
    CODE_OUT_OF_RANGE(MessageTrackerId("01FWKTXVD7GRN5Q8KG39FK090X")),
    SURFACE_TYPE_NOT_ALLOWED_INCISAL(MessageTrackerId("01FWKTXVD857RMXBZDKHVT7ZGJ")),
    SURFACE_TYPE_NOT_ALLOWED_OCCLUSAL(MessageTrackerId("01FXTSG8Z53PG1JPAG867MJ6XZ")),
    SURFACE_TYPE_NOT_ALLOWED_FACIAL(MessageTrackerId("01FXTSG8Z619FBHY10QF033G7Y")),
    SURFACE_TYPE_NOT_ALLOWED_DISTAL(MessageTrackerId("01FXTSG8Z7GRN5Q8KG39FK090X")),
    SURFACE_TYPE_NOT_ALLOWED_MESIAL(MessageTrackerId("01FXTSG8Z72XQ2K4549SYH51FN")),
    SURFACE_TYPE_NOT_ALLOWED_LINGUAL(MessageTrackerId("01FXTSG8Z752MV85FW4ZTYTE6F")),
    SURFACE_TYPE_NOT_ALLOWED_PALATAL(MessageTrackerId("01FXTSG8Z827PHS1MQ52NS823F")),
    NOTE_BIGGER_THAN_ALLOWED(MessageTrackerId("01FWKTXVD8KKHVWHP57PKD8N62")),
    SURFACE_TYPE_CONVERT_FAILED(MessageTrackerId("01FXTSG8Z49FE3F55670TQCPE3")),
    SURFACE_STAMP_CONVERT_FAILED(MessageTrackerId("01FXTSG8Z3Q2MJX8PESM4KVKSP")),
    SIZE_DIFFERENT_THAN_EIGHT(MessageTrackerId("01FXTSG8Z857RMXBZDKHVT7ZGJ")),
    SIZE_DIFFERENT_THAN_FIVE(MessageTrackerId("01FXTSG8Z8KKHVWHP57PKD8N62")),
    ;

    override fun messageTrackerId() = this.messageTrackerId
}