package br.com.acmattos.hdc.person.config

import br.com.acmattos.hdc.common.tool.server.javalin.MessageTracker
import br.com.acmattos.hdc.common.tool.server.javalin.MessageTrackerId

/**
 * @author ACMattos
 * @since 27/10/2021.
 */
enum class MessageTrackerCodeEnum(
    val messageTrackerId: MessageTrackerId
): MessageTracker {
    PERSON_ALREADY_EXISTS(MessageTrackerId("01FJZAFP3DKTN1BYZW6BRHFZFJ")),
    PERSON_NOT_DEFINED(MessageTrackerId("01FWKTXVD4Q2MJX8PESM4KVKSP")),
    PERSON_TYPE_CONVERT_FAILED(MessageTrackerId("01FJZAF4M4KTN1BYZW6BRHFZFJ")),
    STATUS_CONVERT_FAILED(MessageTrackerId("01FVT3QG3R57RMXBZDKHVT7ZGJ")),
    STATE_CONVERT_FAILED(MessageTrackerId("01FJZAGRRNKTN1BYZW6BRHFZFJ")),
    CONTACT_TYPE_CONVERT_FAILED(MessageTrackerId("01FVQ2NP5J19FBHY10QF033G7Y")),
    MARITAL_STATUS_CONVERT_FAILED(MessageTrackerId("01FVT3QG3SKKHVWHP57PKD8N62")),
    DENTIST_ID_INVALID(MessageTrackerId("01FKKM1GEHKTN1BYZW6BRHFZFJ")),
    INVALID_PERSON_FULL_NAME(MessageTrackerId("01FV2HXNN69FE3F55670TQCPE3")),
    INVALID_PERSON_PERSON_TYPE_DENTIST(MessageTrackerId("01FVT5ENFKQ2MJX8PESM4KVKSP")),
    INVALID_PERSON_PERSON_TYPE_PATIENT(MessageTrackerId("01FVT5ENFN9FE3F55670TQCPE3")),
    INVALID_PERSON_OCCUPATION(MessageTrackerId("01FVT5ENFP3PG1JPAG867MJ6XZ")),
    INVALID_PERSON_INDICATED_BY(MessageTrackerId("01FWKSM5K552MV85FW4ZTYTE6F")),
    INVALID_PERSON_ADDRESSES(MessageTrackerId("01FVT5ENFQ19FBHY10QF033G7Y")),
    INVALID_PERSON_CONTACTS(MessageTrackerId("01FVT5ENFQGRN5Q8KG39FK090X")),
    INVALID_PERSON_CPF(MessageTrackerId("01FVPVJN7G27PHS1MQ52NS823F")),
    INVALID_PERSON_DOB(MessageTrackerId("01FWKSM5K19FE3F55670TQCPE3")),
    INVALID_PERSON_PERSONAL_ID(MessageTrackerId("01FVPVJN7H57RMXBZDKHVT7ZGJ")),
    INVALID_PERSON_STATUS(MessageTrackerId("01FWKFTFMM57RMXBZDKHVT7ZGJ")),
    INVALID_PERSON_ADDRESS_STREET(MessageTrackerId("01FVQ2NP5H3PG1JPAG867MJ6XZ")),
    INVALID_PERSON_ADDRESS_NUMBER(MessageTrackerId("01FWKFTFMG9FE3F55670TQCPE3")),
    INVALID_PERSON_ADDRESS_COMPLEMENT(MessageTrackerId("01FVQ2NP5KGRN5Q8KG39FK090X")),
    INVALID_PERSON_ADDRESS_ZIP_CODE(MessageTrackerId("01FVPVJN7D9FE3F55670TQCPE3")),
    INVALID_PERSON_ADDRESS_NEIGHBORHOOD(MessageTrackerId("01FVPVJN7FGRN5Q8KG39FK090X")),
    INVALID_PERSON_ADDRESS_CITY(MessageTrackerId("01FVPVJN7F2XQ2K4549SYH51FN")),
    INVALID_PERSON_CONTACT_INFO(MessageTrackerId("01FVT5ENFTKKHVWHP57PKD8N62")),
    INVALID_PERSON_CONTACT_OBS(MessageTrackerId("01FWKSM5K657RMXBZDKHVT7ZGJ")),
    INVALID_PERSON_DENTAL_PLAN_NAME(MessageTrackerId("01FVPVJN7HKKHVWHP57PKD8N62")),
    INVALID_PERSON_DENTAL_PLAN_NUMBER(MessageTrackerId("01FVQ2NP5FQ2MJX8PESM4KVKSP"));

    override fun messageTrackerId() = this.messageTrackerId
}
